### ISSUE TITLE
[Feature Request] Set Repeat

### ISSUE THREAD

**Issue by kmarker1101** [dwaring87/rtm-cli#13]
Any way to set the repeat schedule from the cli? I did not see anything in the RTM API docs so probably not.

Thanks

**Comment by kmarker1101** [comment]
Lets close this. I figured it out, you just a * before repeat interval.

**Comment by dwaring87** [comment]
Yep, you got it.

In case anyone else comes across this issue, new tasks are parsed by RTM using their [Smart Add Syntax](https://www.rememberthemilk.com/help/answer/basics-smartadd-howdoiuse).  To create a repetitive task, add a `*` followed by a supported [repeat interval](https://www.rememberthemilk.com/help/answer/basics-basics-repeatformat).
