### ISSUE TITLE
Usage of underscore in lists

### ISSUE THREAD

**Issue by michaelonken** [dwaring87/rtm-cli#14]
I have some lists that use an underscore character ('_'), e.g. as in "MY_Tasks".
If I use something like "rtm ls list:MY_Tasks" that should display that list, right?

I am a new user, so sorry if I miss something obvious...:-)

I'm on linux (bash), used the latest binary release.

**Comment by dwaring87** [comment]
You are correct, that should display the tasks in that list.  Are you receiving an error message?  What happens when you run the command `rtm ls`?  Does the output include the `My_Tasks` list with tasks in it?

**Comment by michaelonken** [comment]
The underscore filter results in 
`✖ No tasks returned`

The unfiltered search returns My_Tasks (and other lists) as expected. Thanks!

**Comment by dwaring87** [comment]
I can't replicate this issue - filtering by a list with an underscore in the name works with my account
