### ISSUE TITLE
unexpected end of JSON input

### ISSUE THREAD

**Issue by yina** [dwaring87/rtm-cli#17]
running "rtm ls" produces a syntax error:

```ERROR: SyntaxError: /Users/<userdir>/.rtm.indexcache.json: Unexpected end of JSON input```

I run a script daily and sometime in the past, it just started to fail.

did something change at the api level from RTM? Any thoughts appreciated.

**Comment by yina** [comment]
figured it out. just have to delete a corrupt .rtm.indexcache.json.

**Comment by dwaring87** [comment]
That file is created by `rtm-api` to keep a list of index numbers associated with each task.  Let me know if becomes corrupt again as that's something I'll have to look into.

**Comment by yina** [comment]
It wasn't corrupt as much as it was just a blank file that once I deleted, was regenerated, and all is well. However will let you know if it happens again. thank you!
