### ISSUE TITLE
rm - Service currently unavailable

### ISSUE THREAD

**Issue by paulstodghill** [dwaring87/rtm-cli#18]
Recently, I have started receiving the following message when I attempt to `rm` a task:

~~~~
 [error] Could not remove Task #1 (Service currently unavailable)
~~~~

I am using version 1.5.1. Here is an example sesssion:

~~~~
$ rtm
Logged In As:DELETED
> ls -p
[error] No tasks returned
> add foo
[ok] Task(s) Added
> ls -p
  Inbox
5     foo
> rm 5
[error] Could not remove Task #5 (Service currently unavailable)
[ok] Task(s) Removed
> ls -p
  Inbox
5     foo
> quit
$ 
~~~~

Previously, this same sequence of commands would have successfully deleted task 5. I've tried removing `~/.rtm.indexcache.json` and `~/.rtm.json` and re-authenticating. I've tried multiple computers running, e.g., Ubuntu 19.10, Debian 10.2 and MacOS 10.14, and none work.

Any ideas? Thanks.

**Comment by dwaring87** [comment]
When did you start receiving this error?  I'm getting the same error when I try to remove a task, so it's not related to your account.  The 'Service currently available' message is coming directly from the RTM API server, so it seems like it's a problem on the API Server end.  If it continues I can reach out to them to see if it's a known problem.

**Comment by paulstodghill** [comment]
I could not tell you for certain, but I believe that it has been within the last 7-10 days.

**Comment by dwaring87** [comment]
This was addressed by someone at RTM as a problem on their end that should be fixed now.  Let me know if it's still an issue.
