### ISSUE TITLE
Unable to filter directly by compound names with white spaces

### ISSUE THREAD

**Issue by ajmasia** [dwaring87/rtm-cli#20]
Hi @dwaring87,

I am trying to list the contents of a list whose name is made up of several separate words. The command does not return any value. Example list name: **Could start with**

I try to run the command `rtm ls list:"Could start with*"` and return `No tasks returned`

However if I enter the CLI mode, if it works:

```bash
rtm 
> ls list:"Could start with*"`
```

If the list name does not contain blank spaces, it works directly from the terminal. Otherwise, you need to enter the RTM CLI.

Would it be possible to solve this?

Thanks!

**Comment by douglasfsmn** [comment]
Hi @ajmasia,

Try putting single quotes around the filter portion when running from the command line.  What do you get?
rtm ls 'list:"Could start with*"'
