### ISSUE TITLE
rtm url command hangs

### ISSUE THREAD

**Issue by beauraines** [dwaring87/rtm-cli#21]
When I run the command `rtm url 3163`, the spinner starts and after about 15 seconds it stops spinning and the command hangs. The only way I can stop it is to kill it at this point. I can `CTRL+C` out if I do it while the spinner is still spinning.

I think that this may be a scaling problem; I'm a long time RTM user (over 14 years) and have _a lot_ of tasks. I think that when the `user.tasks.getTask()` runs as part of the `url` command, it is pulling back all my tasks, twice and then has to iteratively scan through all my lists and taskseries to find the matching taskseries.

I let it sit overnight, but still nothing.

I'm not 100% sure if this is a rtm-api or rtm-cli issue. 

I couldn't quite figure out `user.tasks.getTask()` and it's interactions with  `_getTaskInfo()` but I think I have a solution that leverages information from the cache to help pre-filter pulling the task information. I need to abstract it to a function and will share my code when I'm part way through, hopefully for some feedback.  

I think that my solution, ultimately getting a taskseries by cache index, might help with #19 (or at least getting the notes) and #6 , too.

**Comment by dwaring87** [comment]
This should be addressed by 3b7ce730258d103b158ec3ffa64cfa081a43c525.

Unless the RTM API adds a method for getting a single task, performance could continue to be an issue if there are a lot of old tasks in an account.  In this case, it might be best to remove old tasks periodically.
