### ISSUE TITLE
rtm-cli add is not compatible with the standard smart add syntax

### ISSUE THREAD

**Issue by ndom91** [dwaring87/rtm-cli#7]
For example, to add an identical note in rtm-cli and rtm smart add I would have to do the following:

**rtm-cli:** <code>rtm-cli add test note l:Work t:Project1 due:Tomorrow</code>

**rtm smart add:** <code>test note #Work #Project1 ^Tomorrow</code>

I've tested the above two statements, for example, on each input method (rtm-cli and smart add) and I can confirm that at least these three tags (list, tag and due date) do not get recognized by the other service. 

Is there anyway we can harmonize this so there is not a need to memorize two totally different sets of syntax for the same task..

**Comment by dwaring87** [comment]
Thanks for the feedback.

The `add` command arguments are passed directly to RTM and are parsed using their "Smart Add" syntax.  That means you can use `rtm-cli` to add a task using the smart add syntax:

```
rtm add test note #Work #Project1 ^tomorrow
```

and the task should be added to the `Work` list with the `Project1` tag with a due date of `tomorrow`.

The `l:list name`, `t:tag` and `due:due date` syntax is optional but may be helpful when the `#` and/or `^` characters need to escaped at the command line.

So the following command should be equivalent to the first:

```
rtm add test note l:Work t:Project1 due:tomorrow
```

**Comment by ndom91** [comment]
Thanks, I'll give it another shot on rtm-cli with the # + ^ syntax - thats the one I prefer at least.
